#!/bin/bash

# Mow Bros Website - Image Setup Script
# This script helps organize your images from the Wix site

echo "🎨 Mow Bros Website - Image Setup"
echo "=================================="
echo ""

PROJECT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ASSETS_DIR="$PROJECT_DIR/assets/images"
GALLERY_DIR="$PROJECT_DIR/assets/gallery"

# Create directories if they don't exist
mkdir -p "$ASSETS_DIR"
mkdir -p "$GALLERY_DIR"

echo "✅ Directories created:"
echo "   - $ASSETS_DIR"
echo "   - $GALLERY_DIR"
echo ""

echo "📥 Instructions for adding your images:"
echo ""
echo "1️⃣  Download from your Wix site:"
echo "    - Open: https://mowbrosmn.wixsite.com/mow-bros"
echo "    - Right-click each image → 'Save image as...'"
echo "    - Save to your Downloads folder"
echo ""
echo "2️⃣  Required images from Wix site:"
echo "    □ Mow Bros Logo Left to Right.png      → Save as: logo.png"
echo "    □ pexels-pixabay-280222.jpg            → Save as: hero-lawn.jpg"
echo "    □ DJI_0197.JPG                         → Save as: drone-shot.jpg"
echo "    □ 2.png (footer logo)                  → Save as: footer-logo-1.png"
echo "    □ 3.png (footer logo)                  → Save as: footer-logo-2.png"
echo ""
echo "3️⃣  Move images to correct folders:"
echo ""
echo "    For macOS/Linux, run these commands:"
echo "    cd $ASSETS_DIR"
echo "    mv ~/Downloads/logo.png ."
echo "    mv ~/Downloads/hero-lawn.jpg ."
echo "    mv ~/Downloads/drone-shot.jpg ."
echo "    mv ~/Downloads/footer-logo-1.png ."
echo "    mv ~/Downloads/footer-logo-2.png ."
echo ""
echo "4️⃣  (Optional) Add gallery images:"
echo "    cd $GALLERY_DIR"
echo "    mv ~/Downloads/project-*.jpg ."
echo ""
echo "5️⃣  After adding images, test locally:"
echo "    open $PROJECT_DIR/index.html"
echo ""
echo "6️⃣  Upload to GitHub:"
echo "    cd $PROJECT_DIR"
echo "    git add assets/"
echo "    git commit -m 'Add website images'"
echo "    git push"
echo ""
echo "✨ Your website will be live at:"
echo "   https://benjitaught.github.io/Mow-Bros-Website"
echo ""
echo "📚 For detailed instructions, see: ASSETS_GUIDE.md"
echo ""
